function varargout = sudoku_export(varargin)
% SUDOKU_EXPORT MATLAB code for sudoku_export.fig
%      SUDOKU_EXPORT, by itself, creates a new SUDOKU_EXPORT or raises the existing
%      singleton*.
%
%      H = SUDOKU_EXPORT returns the handle to a new SUDOKU_EXPORT or the handle to
%      the existing singleton*.
%
%      SUDOKU_EXPORT('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SUDOKU_EXPORT.M with the given input arguments.
%
%      SUDOKU_EXPORT('Property','Value',...) creates a new SUDOKU_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before sudoku_export_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to sudoku_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help sudoku_export

% Last Modified by GUIDE v2.5 30-Oct-2017 08:57:48

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @sudoku_export_OpeningFcn, ...
                   'gui_OutputFcn',  @sudoku_export_OutputFcn, ...
                   'gui_LayoutFcn',  @sudoku_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before sudoku_export is made visible.
function sudoku_export_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to sudoku_export (see VARARGIN)

% 定时器初始化
handles.ht = timer;                                     % 定义定时器
set(handles.ht, 'ExecutionMode', 'FixedRate');          % ExecutionMode   执行的模式
set(handles.ht, 'Period', 1);                           % 周期
set(handles.ht, 'TimerFcn', {@dispTime, handles});      % 定时器执行函数
start(handles.ht);                                      % 启动定时器

% 位置初始化
handles.selectLoc = 0;

% 填充计数器初始化
handles.fillNum = 0;

% 留空的数量
handles.dragNum = 20;

% 地图初始化
[gameMap, showMap] = genSudoku(handles.dragNum);
handles.gameMap = gameMap;
handles.showMap = showMap;

% 初始化显示
for aa = 1:81
    if showMap(aa) ~= 0
        eval(sprintf('set(handles.pushbutton%d, ''String'', ''%d'')', aa, showMap(aa)))
        eval(sprintf('set(handles.pushbutton%d, ''Enable'', ''inactive'')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''ForegroundColor'', [0 0 0])', aa))
    else
        eval(sprintf('set(handles.pushbutton%d, ''String'', '''')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''Enable'', ''on'')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''ForegroundColor'', [0 0 1])', aa))
    end
end

% Choose default command line output for sudoku_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes sudoku_export wait for user response (see UIRESUME)
% uiwait(handles.figure1);

% 定时器的执行函数 
function dispTime(hObject, eventdata, handles)

set(handles.text3, 'string', datestr(now))


% --- Outputs from this function are returned to the command line.
function varargout = sudoku_export_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% 生成数独矩阵
function [gameMap, showMap] = genSudoku(dragNum)

gameMap = zeros(9);
gameMap(:,1) = randperm(9)';

mapInfo = cell(81, 1);

aa = 10;
debugCount = 0;

while aa <= 81

    debugCount = debugCount + 1;
    
    % 索引错误进入调试
    if aa < 10
        keyboard
    end

    if isempty(mapInfo{aa})

        % 初次到达, 获取节点信息
        temp = possibleNum(gameMap, aa);
        mapInfo{aa} = temp;

    else

        % 回溯到达, 剪枝
        temp = mapInfo{aa};
        temp = temp(temp ~= gameMap(aa));
        mapInfo{aa} = temp;

    end

    if isempty(temp)

        % 节点无法填充, 回溯
        gameMap(aa) = 0;
        aa = aa - 1;

    else

        % 节点可以填充, 填充并前进
        gameMap(aa) = temp(1);
        aa = aa + 1;

    end

end

dragLoc = randperm(81, dragNum);
showMap = gameMap;
showMap(dragLoc) = 0;



% 检查是否符合数独要求
function isUnique = checkUnique(gameMap, ind)

[x, y] = ind2sub([9, 9], ind);
isUnique = true;

% 检查行
ChosenRow = gameMap(x,gameMap(x,:)>0);
if length(unique(ChosenRow)) < length(ChosenRow)
    isUnique = false;
end

% 检查列
ChosenCol = gameMap(gameMap(:,y)>0,y);
if length(unique(ChosenCol)) < length(ChosenCol)
    isUnique = false;
end

% 检查区域
areaX = 3 * floor(x/3.01) + (1:3);
areaY = 3 * floor(y/3.01) + (1:3);
ChosenArea = reshape(gameMap(areaX, areaY), 1, []);
ChosenArea = ChosenArea(ChosenArea>0);
if length(unique(ChosenArea)) < length(ChosenArea)
    isUnique = false;
end


% 每个位置允许填写的数字
function rsl = possibleNum(gameMap, ind)

[x, y] = ind2sub([9, 9], ind);
areaX = 3 * floor(x/3.01) + (1:3);
areaY = 3 * floor(y/3.01) + (1:3);

ChosenRow = gameMap(x,:);
ChosenCol = gameMap(:,y);
ChosenArea = reshape(gameMap(areaX, areaY), 1, []);

used = unique([ChosenRow, ChosenCol', ChosenArea]);
rsl = setdiff(1:9, used);


% --- Executes on button press in pushbuttonSent.
function pushbuttonSent_Callback(hObject, eventdata, handles)
% hObject    handle to pushbuttonSent (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% 未选择, 不做响应
if handles.selectLoc == 0
    return
end

% 获取输入
NumIn = str2num(get(handles.edit1, 'String'));
loc = handles.selectLoc;

% 输入不在1-9之间, 不做响应
if isempty(NumIn) || NumIn > 9 || NumIn < 1
    return
end

% 显示
eval(sprintf('set(handles.pushbutton%d, ''String'', ''%d'')', loc, NumIn))

% 增加填充计数器
if handles.showMap(loc) == 0
    handles.fillNum = handles.fillNum + 1;
end

% 记录填充数字
handles.showMap(loc) = NumIn;

% 如果所有位置被填充, 结束游戏
if handles.fillNum == handles.dragNum
    
    % 检查填充是否正确
    isRight = true;
    for aa = 1:81
        if ~checkUnique(handles.showMap, aa)
            isRight = false;
            break
        end
    end
    
    if isRight
        hlt = msgbox('');
        texth = findall(hlt, 'Type', 'Text');
        set(texth, 'FontSize', 16, 'HorizontalAlignment', 'center', 'String', '真慢╮(╯▽╰)╭')
        set(texth, 'Position', [62.5 26 125])
        pushbuttonh =  findall(hlt, 'Style', 'pushbutton');
        set(pushbuttonh, 'Callback', {@pushbuttonMsgClose_Callback, handles, hlt})
    else
        hlt = msgbox('');
        texth = findall(hlt, 'Type', 'Text');
        set(texth, 'FontSize', 16, 'HorizontalAlignment', 'center', 'String', '真菜')
        set(texth, 'Position', [62.5 26 125])
        pushbuttonh =  findall(hlt, 'Style', 'pushbutton');
        set(pushbuttonh, 'Callback', {@pushbuttonMsgClose_Callback, handles, hlt})
    end
    
end


% Update handles structure
guidata(hObject, handles);


% --- Executes on button press in pushbuttonRestart.
function pushbuttonRestart_Callback(hObject, eventdata, handles)
% hObject    handle to pushbuttonRestart (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% 位置初始化
handles.selectLoc = 0;

% 填充计数器初始化
handles.fillNum = 0;

% 获取留空数量输入
NumIn = str2num(get(handles.edit2, 'String'));

% 输入不在0-81之间, 提示错误
if isempty(NumIn) || NumIn > 81 || NumIn < 0
    'pass';
else
    handles.dragNum = NumIn;
end


% 地图初始化
[gameMap, showMap] = genSudoku(handles.dragNum);
handles.gameMap = gameMap;
handles.showMap = showMap;

% 初始化显示
for aa = 1:81
    if showMap(aa) ~= 0
        eval(sprintf('set(handles.pushbutton%d, ''String'', ''%d'')', aa, showMap(aa)))
        eval(sprintf('set(handles.pushbutton%d, ''Enable'', ''inactive'')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''ForegroundColor'', [0 0 0])', aa))
    else
        eval(sprintf('set(handles.pushbutton%d, ''String'', '''')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''Enable'', ''on'')', aa))
        eval(sprintf('set(handles.pushbutton%d, ''ForegroundColor'', [0 0 1])', aa))
    end
end

% Choose default command line output for sudoku_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);


% --- Executes on button press in pushbuttonMsgClose.
function pushbuttonMsgClose_Callback(hObject, eventdata, handles, hlt)

% 重置游戏
pushbuttonRestart_Callback(handles.pushbuttonRestart, eventdata, handles)

% 关闭消息窗口
close(hlt)






function edit1_Callback(hObject, eventdata, handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit1 as text
%        str2double(get(hObject,'String')) returns contents of edit1 as a double


% --- Executes during object creation, after setting all properties.
function edit1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


function edit2_Callback(hObject, eventdata, handles)
% hObject    handle to edit2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit2 as text
%        str2double(get(hObject,'String')) returns contents of edit2 as a double


% --- Executes during object creation, after setting all properties.
function edit2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end








function pushbutton1_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 1;

% Update handles structure
guidata(hObject, handles);


function pushbutton2_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 2;

% Update handles structure
guidata(hObject, handles);


function pushbutton3_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 3;

% Update handles structure
guidata(hObject, handles);


function pushbutton4_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 4;

% Update handles structure
guidata(hObject, handles);


function pushbutton5_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 5;

% Update handles structure
guidata(hObject, handles);


function pushbutton6_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 6;

% Update handles structure
guidata(hObject, handles);


function pushbutton7_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 7;

% Update handles structure
guidata(hObject, handles);


function pushbutton8_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 8;

% Update handles structure
guidata(hObject, handles);


function pushbutton9_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 9;

% Update handles structure
guidata(hObject, handles);


function pushbutton10_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 10;

% Update handles structure
guidata(hObject, handles);


function pushbutton11_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 11;

% Update handles structure
guidata(hObject, handles);


function pushbutton12_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 12;

% Update handles structure
guidata(hObject, handles);


function pushbutton13_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 13;

% Update handles structure
guidata(hObject, handles);


function pushbutton14_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 14;

% Update handles structure
guidata(hObject, handles);


function pushbutton15_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 15;

% Update handles structure
guidata(hObject, handles);


function pushbutton16_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 16;

% Update handles structure
guidata(hObject, handles);


function pushbutton17_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 17;

% Update handles structure
guidata(hObject, handles);


function pushbutton18_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 18;

% Update handles structure
guidata(hObject, handles);


function pushbutton19_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 19;

% Update handles structure
guidata(hObject, handles);


function pushbutton20_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 20;

% Update handles structure
guidata(hObject, handles);


function pushbutton21_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 21;

% Update handles structure
guidata(hObject, handles);


function pushbutton22_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 22;

% Update handles structure
guidata(hObject, handles);


function pushbutton23_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 23;

% Update handles structure
guidata(hObject, handles);


function pushbutton24_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 24;

% Update handles structure
guidata(hObject, handles);


function pushbutton25_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 25;

% Update handles structure
guidata(hObject, handles);


function pushbutton26_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 26;

% Update handles structure
guidata(hObject, handles);


function pushbutton27_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 27;

% Update handles structure
guidata(hObject, handles);


function pushbutton28_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 28;

% Update handles structure
guidata(hObject, handles);


function pushbutton29_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 29;

% Update handles structure
guidata(hObject, handles);


function pushbutton30_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 30;

% Update handles structure
guidata(hObject, handles);


function pushbutton31_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 31;

% Update handles structure
guidata(hObject, handles);


function pushbutton32_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 32;

% Update handles structure
guidata(hObject, handles);


function pushbutton33_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 33;

% Update handles structure
guidata(hObject, handles);


function pushbutton34_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 34;

% Update handles structure
guidata(hObject, handles);


function pushbutton35_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 35;

% Update handles structure
guidata(hObject, handles);


function pushbutton36_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 36;

% Update handles structure
guidata(hObject, handles);


function pushbutton37_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 37;

% Update handles structure
guidata(hObject, handles);


function pushbutton38_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 38;

% Update handles structure
guidata(hObject, handles);


function pushbutton39_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 39;

% Update handles structure
guidata(hObject, handles);


function pushbutton40_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 40;

% Update handles structure
guidata(hObject, handles);


function pushbutton41_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 41;

% Update handles structure
guidata(hObject, handles);


function pushbutton42_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 42;

% Update handles structure
guidata(hObject, handles);


function pushbutton43_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 43;

% Update handles structure
guidata(hObject, handles);


function pushbutton44_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 44;

% Update handles structure
guidata(hObject, handles);


function pushbutton45_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 45;

% Update handles structure
guidata(hObject, handles);


function pushbutton46_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 46;

% Update handles structure
guidata(hObject, handles);


function pushbutton47_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 47;

% Update handles structure
guidata(hObject, handles);


function pushbutton48_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 48;

% Update handles structure
guidata(hObject, handles);


function pushbutton49_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 49;

% Update handles structure
guidata(hObject, handles);


function pushbutton50_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 50;

% Update handles structure
guidata(hObject, handles);


function pushbutton51_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 51;

% Update handles structure
guidata(hObject, handles);


function pushbutton52_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 52;

% Update handles structure
guidata(hObject, handles);


function pushbutton53_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 53;

% Update handles structure
guidata(hObject, handles);


function pushbutton54_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 54;

% Update handles structure
guidata(hObject, handles);


function pushbutton55_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 55;

% Update handles structure
guidata(hObject, handles);


function pushbutton56_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 56;

% Update handles structure
guidata(hObject, handles);


function pushbutton57_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 57;

% Update handles structure
guidata(hObject, handles);


function pushbutton58_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 58;

% Update handles structure
guidata(hObject, handles);


function pushbutton59_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 59;

% Update handles structure
guidata(hObject, handles);


function pushbutton60_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 60;

% Update handles structure
guidata(hObject, handles);


function pushbutton61_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 61;

% Update handles structure
guidata(hObject, handles);


function pushbutton62_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 62;

% Update handles structure
guidata(hObject, handles);


function pushbutton63_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 63;

% Update handles structure
guidata(hObject, handles);


function pushbutton64_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 64;

% Update handles structure
guidata(hObject, handles);


function pushbutton65_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 65;

% Update handles structure
guidata(hObject, handles);


function pushbutton66_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 66;

% Update handles structure
guidata(hObject, handles);


function pushbutton67_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 67;

% Update handles structure
guidata(hObject, handles);


function pushbutton68_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 68;

% Update handles structure
guidata(hObject, handles);


function pushbutton69_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 69;

% Update handles structure
guidata(hObject, handles);


function pushbutton70_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 70;

% Update handles structure
guidata(hObject, handles);


function pushbutton71_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 71;

% Update handles structure
guidata(hObject, handles);


function pushbutton72_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 72;

% Update handles structure
guidata(hObject, handles);


function pushbutton73_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 73;

% Update handles structure
guidata(hObject, handles);


function pushbutton74_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 74;

% Update handles structure
guidata(hObject, handles);


function pushbutton75_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 75;

% Update handles structure
guidata(hObject, handles);


function pushbutton76_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 76;

% Update handles structure
guidata(hObject, handles);


function pushbutton77_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 77;

% Update handles structure
guidata(hObject, handles);


function pushbutton78_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 78;

% Update handles structure
guidata(hObject, handles);


function pushbutton79_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 79;

% Update handles structure
guidata(hObject, handles);


function pushbutton80_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 80;

% Update handles structure
guidata(hObject, handles);


function pushbutton81_Callback(hObject, eventdata, handles)

% 选中坐标
handles.selectLoc = 81;

% Update handles structure
guidata(hObject, handles);





% --- Creates and returns a handle to the GUI figure. 
function h1 = sudoku_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 5, ...
    'pushbutton', 85, ...
    'edit', 3), ...
    'override', 0, ...
    'release', [], ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'E:\编程\matlab\matlab函数\project\数学建模实践\数独\sudoku_export.m', ...
    'lastFilename', 'E:\编程\matlab\matlab函数\project\数学建模实践\数独\sudoku.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits','inches',...
'Units','characters',...
'Position',[135.8 41.1703296703297 153.6 43.2142857142857],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','sudoku',...
'NumberTitle','off',...
'Tag','figure1',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[8.5 11],...
'PaperSizeMode',get(0,'defaultfigurePaperSizeMode'),...
'PaperType','usletter',...
'PaperTypeMode',get(0,'defaultfigurePaperTypeMode'),...
'PaperUnitsMode',get(0,'defaultfigurePaperUnitsMode'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton1';

h2 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbutton1',...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton2';

h3 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton2',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton3';

h4 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton3',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton4';

h5 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton4',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton5';

h6 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton5_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton5',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton6';

h7 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton6_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton6',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton7';

h8 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton7_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton7',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton8';

h9 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton8_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton8',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton9';

h10 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[16 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton9_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton9',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton10';

h11 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton10_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton10',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton11';

h12 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton11_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton11',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton12';

h13 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton12_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton12',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton13';

h14 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton13_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton13',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton14';

h15 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton14_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton14',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton15';

h16 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton15_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton15',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton16';

h17 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton16_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton16',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton17';

h18 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton17_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton17',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton18';

h19 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[27.2 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton18_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton18',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton19';

h20 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton19_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton19',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton20';

h21 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton20_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton20',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton21';

h22 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton21_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton21',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton22';

h23 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton22_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton22',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton23';

h24 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton23_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton23',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton24';

h25 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton24_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton24',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton25';

h26 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton25_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton25',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton26';

h27 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton26_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton26',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton27';

h28 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38.4 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton27_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton27',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton28';

h29 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton28_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton28',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton29';

h30 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton29_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton29',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton30';

h31 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton30_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton30',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton31';

h32 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 28 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton31_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton31',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton32';

h33 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton32_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton32',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton33';

h34 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton33_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton33',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton34';

h35 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton34_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton34',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton35';

h36 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton35_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton35',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton36';

h37 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[49.6 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton36_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton36',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton37';

h38 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton37_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton37',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton38';

h39 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton38_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton38',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton39';

h40 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton39_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton39',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton40';

h41 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 28 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton40_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton40',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton41';

h42 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton41_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton41',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton42';

h43 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton42_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton42',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton43';

h44 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton43_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton43',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton44';

h45 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton44_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton44',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton45';

h46 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[60.8 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton45_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton45',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton46';

h47 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton46_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton46',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton47';

h48 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton47_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton47',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton48';

h49 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton48_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton48',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton49';

h50 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 28 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton49_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton49',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton50';

h51 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton50_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton50',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton51';

h52 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton51_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton51',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton52';

h53 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton52_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton52',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton53';

h54 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton53_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton53',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton54';

h55 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[72 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton54_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton54',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton55';

h56 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton55_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton55',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton56';

h57 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton56_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton56',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton57';

h58 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton57_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton57',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton58';

h59 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton58_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton58',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton59';

h60 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton59_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton59',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton60';

h61 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton60_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton60',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton61';

h62 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton61_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton61',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton62';

h63 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton62_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton62',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton63';

h64 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[83.2 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton63_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton63',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton64';

h65 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton64_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton64',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton65';

h66 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton65_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton65',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton66';

h67 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton66_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton66',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton67';

h68 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton67_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton67',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton68';

h69 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton68_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton68',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton69';

h70 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton69_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton69',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton70';

h71 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[94.4 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton70_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton70',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'FontSize',20,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pushbutton71';

h72 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton71_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton71',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton72';

h73 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[94.4 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton72_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton72',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton73';

h74 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 37.6428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton73_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton73',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton74';

h75 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 34.4285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton74_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton74',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton75';

h76 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 31.2142857142857 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton75_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton75',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton76';

h77 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 28 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton76_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton76',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton77';

h78 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 24.7857142857143 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton77_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton77',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton78';

h79 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 21.5714285714286 10.8 3.07142857142857],...
'BackgroundColor',[0.8 0.8 0.8],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton78_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton78',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton79';

h80 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 18.3571428571429 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton79_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton79',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton80';

h81 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 15.1428571428571 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton80_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton80',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'pushbutton81';

h82 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[105.6 11.9285714285714 10.8 3.07142857142857],...
'BackgroundColor',[0.901960784313726 0.901960784313726 0.901960784313726],...
'Callback',@(hObject,eventdata)sudoku_export('pushbutton81_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton81',...
'KeyPressFcn',blanks(0),...
'FontSize',20);

appdata = [];
appdata.lastValidTag = 'edit1';

h83 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','0',...
'Style','edit',...
'Position',[129.6 28.7857142857143 18.2 6],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)sudoku_export('edit1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)sudoku_export('edit1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit1',...
'FontSize',32);

appdata = [];
appdata.lastValidTag = 'pushbuttonSent';

h84 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','sent',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[129.6 24.2857142857143 18.2 2.92857142857143],...
'Callback',@(hObject,eventdata)sudoku_export('pushbuttonSent_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbuttonSent',...
'FontSize',24);

appdata = [];
appdata.lastValidTag = 'text2';

h85 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'sudoku'; 'Low到尽头便是潮' },...
'Style','text',...
'Position',[39.8 5.71428571428571 58.2 4.28571428571429],...
'Children',[],...
'ForegroundColor',[0 0 1],...
'Tag','text2',...
'FontSize',18,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h86 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  '静态文本' },...
'Style','text',...
'Position',[22.2 1.42857142857143 97.8 2.42857142857143],...
'Children',[],...
'ForegroundColor',[1 0 0],...
'Tag','text3',...
'FontSize',18,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbuttonRestart';

h87 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','restart',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[127.8 13.0714285714286 21.8 2.92857142857143],...
'Callback',@(hObject,eventdata)sudoku_export('pushbuttonRestart_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbuttonRestart',...
'KeyPressFcn',blanks(0),...
'FontSize',24);

appdata = [];
appdata.lastValidTag = 'edit2';

h88 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','20',...
'Style','edit',...
'Position',[132 16.3571428571429 13.2 2.92857142857143],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)sudoku_export('edit2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)sudoku_export('edit2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit2',...
'FontSize',16);

appdata = [];
appdata.lastValidTag = 'text4';

h89 = uicontrol(...
'Parent',h1,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','留空数量:',...
'Style','text',...
'Position',[128.6 19.7857142857143 20.2 1.92857142857143],...
'Children',[],...
'Tag','text4',...
'FontSize',16,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % SUDOKU_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % SUDOKU_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % SUDOKU_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % SUDOKU_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


